### ISSUE TITLE
Example for find mongodb method

### ISSUE THREAD

**Issue by gmunumel** [lumaghg/denomongo-unittest-utils#9] opened 2022-07-27 15:33 UTC
Hello, 
Thanks for the library. 

This is not a bug but a general question (I don't know if this is the right place for this).

Taking the example of your page as reference:  [https://deno.land/x/denomongo_unittest_utils@v0.5.1](https://deno.land/x/denomongo_unittest_utils@v0.5.1), I want to test the `find` **mongodb** method. For that I need to return a `FindCursor` instead of `Promise`. In the example bellow the context is not well formed, actually I don't know what to pass. Also I tried to stub the method using `sinon` ([https://sinonjs.org/](https://sinonjs.org/)) with not much luck. Any idea or recommendation?

    const allValues = () => {
      try {    
        return prodCollection.find({}, { noCursorTimeout: false }).toArray();
      } catch (error) {
        console.error(error);
      }
    };

    Deno.test("simple example", () => {
        MockCollection.initMock({
            find: (_filter?: Filter<unknown> | undefined, _options?: FindOptions | undefined): Promise<unknown> => {
               const ctx: any = <some context>; 
               return new FindCursor(ctx);
            }
        })
    
        //execute the function
        exampleDatabaseCall()
    
        //check whether the find Method was called correctly and returned the correct values
        assertSpyCallAsync(MockCollection.getInstance().find as Spy<any>, 0, {args: [{id: "example"}, {limit: 1}], returned: {id: "example"}})
    
    })

**Comment by lumaghg** [comment] 2022-07-28 07:16
Hi, 
thank you for your question.

I think the problem is that the example on the page only is for `findOne()`, not `find()`, as they have different signatures. 
We should maybe look into extending the examples or also providing a method to create a FindCursor mock, I think we only looked into the top layer :)

The return type for `find()` is indeed a FindCursor, and you can find the class definition [here](https://deno.land/x/mongo@v0.31.0/src/collection/commands/find.ts?code) as well as the FindCursorContext:
```
interface FindCursorContext {
  dbName: string;
  collectionName: string;
  protocol: WireProtocol;
  options: FindOptions;
  filter?: Document;
}
```
The `WireProtocol` class can be found [here](https://deno.land/x/mongo@v0.31.0/src/protocol/protocol.ts?code).

Let me know if this helps.

Best regards, 
Robin

**Comment by gmunumel** [comment] 2022-07-28 10:07
Thanks for your suggestion @lumaghg . I got this error: 

```
error: (in promise) AssertionError: spy not called as much as expected
    throw new AssertionError("spy not called as much as expected");
          ^
    at assertSpyCallsMin (https://deno.land/x/mock@0.13.0/asserts.ts:148:11)
    at assertSpyCall (https://deno.land/x/mock@0.13.0/asserts.ts:181:3)
    at assertSpyCallAsync (https://deno.land/x/mock@0.13.0/asserts.ts:258:25)
    at fn (file:///home/runner/MongodbUnitTest/tests/resolvers/userResolver_test.ts:35:5)
This error was not caught from a test and caused the test runner to fail on the referenced module.
It most likely originated from a dangling promise, event/timeout handler or top-level code.
```

I made this [replit](https://replit.com/@gmunumel/MongodbUnitTest?v=1#README.md) to see it clearly.

**Comment by lumaghg** [comment] 2022-07-29 07:12
Hello @gmunumel,
I already found a few issues, but I did not have time to implement a solution for them. I will try later, but in the meantime i thought I'd already share them with you so you can also have a go at it.

1. Your importMap does not seem to replace the collection with the denomongo stub. You have to adjust the path in the importMap that should be replaced to your project, as the importMap only replaces the path, that is actually imported. In your example it would be `"../service/collections/userCollection.ts"` because in `userResolver.ts` you import via this path (`import userCollection from "../service/collections/userCollection.ts";`). You can find more information on importMaps [here](https://github.com/WICG/import-maps) and [here](https://deno.land/manual/linking_to_external_code/import_maps).
I would assume that this is the reason your SpyAssertion fails, because the function call is not made on the stub you are inspecting, but on the real collection.

2. In the userResolver_test.ts line 40, you define that there should be no return values in the calls to the `find()` function, even though you do want it to return a `FindCursor` in line 28.

I will have a look at it later, if you make some progress or run into new issues, feel free to post it.

Best regards,
Robin

**Comment by gmunumel** [comment] 2022-07-29 12:48
Thanks for the comments @lumaghg. Your comments are helpful :). I have made an update of my solution. Some remarks:

1. I placed the `importMap.json` file in root folder. Updated the import path to be relative from the root folder. 
2. You need to run it as: `deno test -A --import-map=importMap.json`
3. I mocked the `FindCursor` class but the test fails: 

```
error: AssertionError: spy call did not return expected value:

    [Diff] Actual / Expected

-   FindCursor {}
+   [Function: FindCursor]
```

I tried with `typeof`, `instanceof`, `assertInstanceOf`. None of them work. I googled but didn't find a good solution. 

4. Also found another issue. When you define a `insertOne` in **userResolver.ts** (it's comment now), got another error: 

```
error: TS2345 [ERROR]: Argument of type '{ name: any; last_name: any; dob: any; image_url: any; role: any; username: any; password: any; created_at: Date; updated_at: any; }' is not assignable to parameter of type 'InsertDocument<unknown>'.
  Object literal may only specify known properties, and 'name' does not exist in type 'InsertDocument<unknown>'.
      name: args.name,
      ~~~~~~~~~~~~~~~
```
Only happens when apply the mapping while run the tests, which I infer is a problem with the library. 

Best regards,
Gabriel

**Comment by lumaghg** [comment] 2022-07-30 22:08
Hi @gmunumel,

I think you can fix problem 3 by simply using the `getMockFindCursor()` function to generate the `FindCursor` that you are expecting or the exact same FindCursor you are returning in your Mock. Right now your `expected` is `FindCursor`, which is the class / type you import at the top. 
I will look into problem 4 some time next week and open a new issues.

Hope this helps,
Robin

**Comment by gmunumel** [comment] 2022-07-31 13:32
Hey @lumaghg , yes, I thought on that solution but looks to me like cheating because I already mock `FindCursor` using that instance. It's more like testing the mock instead of testing the `find` of **mongodb**.  But, I agreed that this is a special case. 

Sure. Let me know about your findings. :)

**Comment by lumaghg** [comment] 2022-08-03 08:55
Hi @gmunumel,
the purpose of this module is neither to test the find of the mongodb, nor to test the module :D. It is to mock the mongo call, so that you can unit-test your other application code around it without being dependent on a test-environment with a database (which would already classify as integration test then). 
You can also avoid that one test destroying the testdatabase results in other tests failing, because they are completely independent due to the mock, that by definition always has the same specified behaviour. It gets more and more useful the bigger your project gets.

Hope this provides a little more clarification,
Robin

**Comment by lumaghg** [comment] 2022-08-03 08:59
I have transferred the insertOne issue to #10 and will therefore now close this issue.

**Closed as completed by lumaghg** 2022-08-03 08:59 UTC
Labels: documentation
